logger:
  level: INFO
queue:
  url: amqp://rabbit:password@rabbitmq:5672/
  exchange: calendar
  queue: calendar.notifications
  routing_key: calendar.notification
  consumer_tag: calendar-sender
status_queue:
  url: amqp://rabbit:password@rabbitmq:5672/
  exchange: calendar
  queue: calendar.notification_statuses
  routing_key: calendar.notification.status
