logger:
  level: INFO
storage:
  type: SQL
  dsn: postgres://postgres:password@localhost:5435/backend?sslmode=disable
queue:
  url: amqp://rabbit:password@localhost:5672/
  exchange: calendar
  queue: calendar.notifications
  routing_key: calendar.notification
  consumer_tag: calendar-scheduler
scheduler:
  scan_interval: 1m
  cleanup_interval: 1h
